[package]
name = "tauri-plugin-hyper-fetch"
version = "0.0.0"
authors = ["maemon4095"]
description = ""
edition = "2021"
rust-version = "1.60"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.6.1" }
